### ISSUE TITLE
0.2 operator register and create

### ISSUE THREAD

**Issue by ijackwu** [zilliztech/phantoscope#152]
if more than one machine, how do use operator register and create ,or how do use k8s ?
thank!

**Comment by ABNER-1** [comment]
Hello @ijackwu.
This is a good question.
In phantoscope 0.2.0 verison, local docker runtime is only supported. This feature can be implemented by k8s runtime. 
However, for a period of time, we have no plan to implement this feature due to some reasons.
If you are interested in this work, pull requests welcome!

**Comment by ijackwu** [comment]
@ABNER-1 
I think the 0.1.0 version, operator register  is more free and can support multiple machine.

**Comment by ABNER-1** [comment]
Yes, you are right. 

In 0.1.0, all operator (instance) needs to be started by administrator. Of course, you can deploy whatever you want.

However, when working with more machines, we think this work can be completed by machine to simplified the work of administrator.
Moreover, when we implemented more runtime mode, phantoscope will be more powerful in all suitation.

For example, starting container in runtime means phantoscope operator can be orchestrated by k8s with more strategies, adding load balancer or ingress controller can also be easier.

Thanks for watching phantoscope.

**Comment by ijackwu** [comment]
thinks ！
