### ISSUE TITLE
Can't extract face vector of image

### ISSUE THREAD

**Issue by sunyun0090** [zilliztech/phantoscope#160]
When i user Pipeline：mtcnn-face-detector -> face-encoder get face vectors, I find the pipeline failed to  extract face vector of image1 , but extract face vector of image2 successfully.
![image](https://user-images.githubusercontent.com/14146919/92677062-7b064680-f355-11ea-9230-8101f34b9c55.png)
img 1
![image](https://user-images.githubusercontent.com/14146919/92677069-80639100-f355-11ea-914d-1baf6255a785.png)
img2

**Comment by ABNER-1** [comment]
Can you give me the error of image 1?

I guess that was caused by mtcnn detector threshold. You can decrease the face threshold when apply in this scenario.

Or the first image is too large?
When converted into a fixed size by models, each faces is so little that the score of face has been decreased.
